
export const menProducts = [
  {
    id: 'men-1',
    name: 'Executive Tailored Suit',
    price: 2899,
    image: 'http://pollyannaevents.com/cdn/shop/files/S77c0eec5830f489497e8b6e16475fc11h.webp?v=1748445528',
    category: 'Suits',
    description: 'Handcrafted Italian wool suit with impeccable tailoring and modern silhouette',
  },
  {
    id: 'men-2',
    name: 'Luxury Leather Jacket',
    price: 1799,
    image: 'https://img4.dhresource.com/webp/m/0x0/f3/albu/km/j/20/8872b4d9-3772-4e07-bdb5-9f8dba4c03ea.jpg',
    category: 'Outerwear',
    description: 'Premium Italian leather jacket with contemporary design and superior craftsmanship',
  },
  {
    id: 'men-3',
    name: 'Handcrafted Oxford Shoes',
    price: 899,
    image: 'https://cdn.abacus.ai/images/93db2c6d-7aa5-437b-b267-1f4781b59d94.png',
    category: 'Footwear',
    description: 'Elegant Oxford shoes made from finest Italian leather with Goodyear welt construction',
  },
  {
    id: 'men-4',
    name: 'Italian Luxury Shoes',
    price: 1299,
    image: 'https://italianshoescompany.com/cdn/shop/files/DSC_6551-2.jpg?v=1699263428&width=2048',
    category: 'Footwear',
    description: 'Premium Italian dress shoes with traditional craftsmanship and modern comfort',
  },
  {
    id: 'men-5',
    name: 'Swiss Luxury Timepiece',
    price: 8500,
    image: 'https://i.pinimg.com/736x/04/e4/0c/04e40c26f8412e5220dbdc6cf9a978a5.jpg',
    category: 'Accessories',
    description: 'Sophisticated Swiss-made watch with automatic movement and sapphire crystal',
  },
  {
    id: 'men-6',
    name: 'Designer Leather Briefcase',
    price: 1499,
    image: 'https://i.pinimg.com/736x/8a/d8/0a/8ad80aad3e903614bd1ad283f718ba30.jpg',
    category: 'Bags',
    description: 'Elegant leather briefcase with multiple compartments and premium hardware',
  },
  {
    id: 'men-7',
    name: 'Platinum Collection Suit',
    price: 3499,
    image: 'https://i.ebayimg.com/images/g/ll8AAOSwWkVktleu/s-l1200.jpg',
    category: 'Suits',
    description: 'Ultra-premium suit from our Platinum collection with bespoke details',
  },
  {
    id: 'men-8',
    name: 'Leather Messenger Bag',
    price: 799,
    image: 'https://i5.walmartimages.com/seo/Shoulder-Bag-Leather-Men-s-Bag-Genuine-Leather-Black-Men-s-Designer-Bags-Leather-Crossbody-Bag-for-Men-Messenger-Bags-Handbags_e74abb0b-0ce2-42cb-892c-9f98d2086c1b.0cc475a0e31bc89a1de060d0982c947f.jpeg',
    category: 'Bags',
    description: 'Versatile leather messenger bag perfect for business and casual wear',
  },
]

export const womenProducts = [
  {
    id: 'women-1',
    name: 'Designer Luxury Handbag',
    price: 2299,
    image: 'https://cdn.abacus.ai/images/d64af533-5cc7-48ba-b429-b9fb775022bc.png',
    category: 'Handbags',
    description: 'Exquisite leather handbag with gold hardware and sophisticated design',
  },
  {
    id: 'women-2',
    name: 'Silk Evening Gown',
    price: 1899,
    image: 'https://ae01.alicdn.com/kf/S02dd1d43298f461699ee8b3618c71c61j.jpg',
    category: 'Dresses',
    description: 'Elegant silk evening gown with intricate beadwork and flowing silhouette',
  },
  {
    id: 'women-3',
    name: 'Designer Stiletto Heels',
    price: 899,
    image: 'https://i.pinimg.com/564x/31/1b/da/311bda6c5951a1b1c33f2c5df5376798.jpg',
    category: 'Footwear',
    description: 'Luxurious stiletto heels with patent leather finish and comfortable fit',
  },
  {
    id: 'women-4',
    name: 'Luxury Designer Tote',
    price: 1699,
    image: 'https://i.pinimg.com/736x/da/f6/3d/daf63df826965a793fe249a5d66183a0.jpg',
    category: 'Handbags',
    description: 'Spacious designer tote bag crafted from premium materials',
  },
  {
    id: 'women-5',
    name: 'Diamond Statement Jewelry',
    price: 4500,
    image: 'https://www.thejewelleryeditor.com/media/images_thumbnails/filer_public_thumbnails/filer_public/0c/4c/0c4c360a-fcc9-4beb-a4de-7bc553785d6c/female-jewellery-designers-jeanne-troussant.jpg__1536x0_q75_crop-scale_subsampling-2_upscale-false.jpg',
    category: 'Jewelry',
    description: 'Stunning diamond jewelry piece with contemporary design and exceptional brilliance',
  },
  {
    id: 'women-6',
    name: 'Silk Designer Scarf',
    price: 299,
    image: 'http://empheslifestyle.com/cdn/shop/products/HandrolledLuxury100_SilkScarvesWomen-EmphesLifestyle1_d7fb6521-7049-4878-8f2d-b6aba1a8418f.jpg?v=1675923614',
    category: 'Accessories',
    description: 'Hand-rolled luxury silk scarf with artistic pattern and vibrant colors',
  },
  {
    id: 'women-7',
    name: 'Premium High Heels',
    price: 1299,
    image: 'https://pollyannaevents.com/cdn/shop/files/S14c36490e4e345cca3575ae3cfec4720k.webp?v=1748460338&width=1946',
    category: 'Footwear',
    description: 'Elegant high heels with superior comfort technology and timeless design',
  },
  {
    id: 'women-8',
    name: 'Couture Evening Dress',
    price: 2599,
    image: 'https://ae01.alicdn.com/kf/Se569137b87a64286a65d75f31d0c2ee2R.jpg',
    category: 'Dresses',
    description: 'Breathtaking couture evening dress with intricate detailing and perfect fit',
  },
]

export const childrenProducts = [
  {
    id: 'children-1',
    name: 'Designer Kids Ensemble',
    price: 299,
    image: 'https://i.pinimg.com/736x/9a/71/97/9a719768f8eb15dd94bf412f78170449.jpg',
    category: 'Clothing',
    description: 'Elegant designer outfit perfect for special occasions and formal events',
  },
  {
    id: 'children-2',
    name: 'Luxury Kids Coat',
    price: 399,
    image: 'https://i.pinimg.com/736x/25/df/fc/25dffc7d3031cca10819ec9e1bcd22d6.jpg',
    category: 'Outerwear',
    description: 'Sophisticated coat designed for style-conscious young ones',
  },
  {
    id: 'children-3',
    name: 'Designer Kids Sneakers',
    price: 199,
    image: 'https://i.pinimg.com/736x/70/71/cf/7071cfb06e42e472e94ef5de56b593bb.jpg',
    category: 'Footwear',
    description: 'Comfortable yet stylish sneakers for active children',
  },
  {
    id: 'children-4',
    name: 'Premium Kids Shoes',
    price: 249,
    image: 'https://i.pinimg.com/736x/f9/9f/15/f99f15d84961a3f873e7787e9bc6de10.jpg',
    category: 'Footwear',
    description: 'High-quality shoes combining comfort with sophisticated design',
  },
  {
    id: 'children-5',
    name: 'Elegant Kids Outfit',
    price: 349,
    image: 'https://img4.dhresource.com/webp/m/0x0/f3/albu/km/n/24/b7365714-f701-4f8f-87b8-2e533520c6b9.jpg',
    category: 'Clothing',
    description: 'Beautifully crafted outfit that combines comfort with luxury aesthetics',
  },
  {
    id: 'children-6',
    name: 'Kids Designer Accessories',
    price: 149,
    image: 'https://i.pinimg.com/736x/9d/bd/ec/9dbdec21399d797aabb2a0b75143b356.jpg',
    category: 'Accessories',
    description: 'Charming accessories to complete any young fashionista\'s look',
  },
  {
    id: 'children-7',
    name: 'Designer Kids Footwear',
    price: 229,
    image: 'https://img4.dhresource.com/webp/m/0x0/f3/albu/km/s/27/ec27273c-d6d6-44cf-bfe7-3395223d0a8f.jpg',
    category: 'Footwear',
    description: 'Stylish and comfortable shoes designed specifically for children',
  },
  {
    id: 'children-8',
    name: 'Luxury Kids Fashion Set',
    price: 399,
    image: 'https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/s/02/472e52d5-3c4a-4900-9c74-36accfa13a9f.jpg',
    category: 'Clothing',
    description: 'Complete fashion set that showcases elegance and sophistication for young ones',
  },
]
